// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_player.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_game_5fplayer_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_game_5fplayer_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_game_5fplayer_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_game_5fplayer_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_game_5fplayer_2eproto;
namespace game {
class GamePlayer;
struct GamePlayerDefaultTypeInternal;
extern GamePlayerDefaultTypeInternal _GamePlayer_default_instance_;
class GamePlayer_SkillsEntry_DoNotUse;
struct GamePlayer_SkillsEntry_DoNotUseDefaultTypeInternal;
extern GamePlayer_SkillsEntry_DoNotUseDefaultTypeInternal _GamePlayer_SkillsEntry_DoNotUse_default_instance_;
class Vec3;
struct Vec3DefaultTypeInternal;
extern Vec3DefaultTypeInternal _Vec3_default_instance_;
}  // namespace game
PROTOBUF_NAMESPACE_OPEN
template<> ::game::GamePlayer* Arena::CreateMaybeMessage<::game::GamePlayer>(Arena*);
template<> ::game::GamePlayer_SkillsEntry_DoNotUse* Arena::CreateMaybeMessage<::game::GamePlayer_SkillsEntry_DoNotUse>(Arena*);
template<> ::game::Vec3* Arena::CreateMaybeMessage<::game::Vec3>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace game {

// ===================================================================

class Vec3 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.Vec3) */ {
 public:
  inline Vec3() : Vec3(nullptr) {}
  ~Vec3() override;
  explicit PROTOBUF_CONSTEXPR Vec3(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vec3(const Vec3& from);
  Vec3(Vec3&& from) noexcept
    : Vec3() {
    *this = ::std::move(from);
  }

  inline Vec3& operator=(const Vec3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vec3& operator=(Vec3&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vec3& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vec3* internal_default_instance() {
    return reinterpret_cast<const Vec3*>(
               &_Vec3_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Vec3& a, Vec3& b) {
    a.Swap(&b);
  }
  inline void Swap(Vec3* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vec3* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vec3* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Vec3>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vec3& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Vec3& from) {
    Vec3::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vec3* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.Vec3";
  }
  protected:
  explicit Vec3(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:game.Vec3)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_;
    float y_;
    float z_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5fplayer_2eproto;
};
// -------------------------------------------------------------------

class GamePlayer_SkillsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<GamePlayer_SkillsEntry_DoNotUse, 
    std::string, int32_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<GamePlayer_SkillsEntry_DoNotUse, 
    std::string, int32_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> SuperType;
  GamePlayer_SkillsEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR GamePlayer_SkillsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit GamePlayer_SkillsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const GamePlayer_SkillsEntry_DoNotUse& other);
  static const GamePlayer_SkillsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const GamePlayer_SkillsEntry_DoNotUse*>(&_GamePlayer_SkillsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "game.GamePlayer.SkillsEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_game_5fplayer_2eproto;
};

// -------------------------------------------------------------------

class GamePlayer final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.GamePlayer) */ {
 public:
  inline GamePlayer() : GamePlayer(nullptr) {}
  ~GamePlayer() override;
  explicit PROTOBUF_CONSTEXPR GamePlayer(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GamePlayer(const GamePlayer& from);
  GamePlayer(GamePlayer&& from) noexcept
    : GamePlayer() {
    *this = ::std::move(from);
  }

  inline GamePlayer& operator=(const GamePlayer& from) {
    CopyFrom(from);
    return *this;
  }
  inline GamePlayer& operator=(GamePlayer&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GamePlayer& default_instance() {
    return *internal_default_instance();
  }
  static inline const GamePlayer* internal_default_instance() {
    return reinterpret_cast<const GamePlayer*>(
               &_GamePlayer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GamePlayer& a, GamePlayer& b) {
    a.Swap(&b);
  }
  inline void Swap(GamePlayer* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GamePlayer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GamePlayer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GamePlayer>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GamePlayer& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GamePlayer& from) {
    GamePlayer::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GamePlayer* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.GamePlayer";
  }
  protected:
  explicit GamePlayer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kInventoryFieldNumber = 6,
    kSkillsFieldNumber = 7,
    kPlayerNameFieldNumber = 2,
    kPositionFieldNumber = 3,
    kPlayerIdFieldNumber = 1,
    kHealthFieldNumber = 4,
    kLevelFieldNumber = 5,
  };
  // repeated int32 inventory = 6;
  int inventory_size() const;
  private:
  int _internal_inventory_size() const;
  public:
  void clear_inventory();
  private:
  int32_t _internal_inventory(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_inventory() const;
  void _internal_add_inventory(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_inventory();
  public:
  int32_t inventory(int index) const;
  void set_inventory(int index, int32_t value);
  void add_inventory(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      inventory() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_inventory();

  // map<string, int32> skills = 7;
  int skills_size() const;
  private:
  int _internal_skills_size() const;
  public:
  void clear_skills();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >&
      _internal_skills() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >*
      _internal_mutable_skills();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >&
      skills() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >*
      mutable_skills();

  // string player_name = 2;
  void clear_player_name();
  const std::string& player_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_player_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_player_name();
  PROTOBUF_NODISCARD std::string* release_player_name();
  void set_allocated_player_name(std::string* player_name);
  private:
  const std::string& _internal_player_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_player_name(const std::string& value);
  std::string* _internal_mutable_player_name();
  public:

  // .game.Vec3 position = 3;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::game::Vec3& position() const;
  PROTOBUF_NODISCARD ::game::Vec3* release_position();
  ::game::Vec3* mutable_position();
  void set_allocated_position(::game::Vec3* position);
  private:
  const ::game::Vec3& _internal_position() const;
  ::game::Vec3* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::game::Vec3* position);
  ::game::Vec3* unsafe_arena_release_position();

  // int32 player_id = 1;
  void clear_player_id();
  int32_t player_id() const;
  void set_player_id(int32_t value);
  private:
  int32_t _internal_player_id() const;
  void _internal_set_player_id(int32_t value);
  public:

  // int32 health = 4;
  void clear_health();
  int32_t health() const;
  void set_health(int32_t value);
  private:
  int32_t _internal_health() const;
  void _internal_set_health(int32_t value);
  public:

  // int32 level = 5;
  void clear_level();
  int32_t level() const;
  void set_level(int32_t value);
  private:
  int32_t _internal_level() const;
  void _internal_set_level(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:game.GamePlayer)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > inventory_;
    mutable std::atomic<int> _inventory_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        GamePlayer_SkillsEntry_DoNotUse,
        std::string, int32_t,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> skills_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr player_name_;
    ::game::Vec3* position_;
    int32_t player_id_;
    int32_t health_;
    int32_t level_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5fplayer_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vec3

// float x = 1;
inline void Vec3::clear_x() {
  _impl_.x_ = 0;
}
inline float Vec3::_internal_x() const {
  return _impl_.x_;
}
inline float Vec3::x() const {
  // @@protoc_insertion_point(field_get:game.Vec3.x)
  return _internal_x();
}
inline void Vec3::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void Vec3::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:game.Vec3.x)
}

// float y = 2;
inline void Vec3::clear_y() {
  _impl_.y_ = 0;
}
inline float Vec3::_internal_y() const {
  return _impl_.y_;
}
inline float Vec3::y() const {
  // @@protoc_insertion_point(field_get:game.Vec3.y)
  return _internal_y();
}
inline void Vec3::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void Vec3::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:game.Vec3.y)
}

// float z = 3;
inline void Vec3::clear_z() {
  _impl_.z_ = 0;
}
inline float Vec3::_internal_z() const {
  return _impl_.z_;
}
inline float Vec3::z() const {
  // @@protoc_insertion_point(field_get:game.Vec3.z)
  return _internal_z();
}
inline void Vec3::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void Vec3::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:game.Vec3.z)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// GamePlayer

// int32 player_id = 1;
inline void GamePlayer::clear_player_id() {
  _impl_.player_id_ = 0;
}
inline int32_t GamePlayer::_internal_player_id() const {
  return _impl_.player_id_;
}
inline int32_t GamePlayer::player_id() const {
  // @@protoc_insertion_point(field_get:game.GamePlayer.player_id)
  return _internal_player_id();
}
inline void GamePlayer::_internal_set_player_id(int32_t value) {
  
  _impl_.player_id_ = value;
}
inline void GamePlayer::set_player_id(int32_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:game.GamePlayer.player_id)
}

// string player_name = 2;
inline void GamePlayer::clear_player_name() {
  _impl_.player_name_.ClearToEmpty();
}
inline const std::string& GamePlayer::player_name() const {
  // @@protoc_insertion_point(field_get:game.GamePlayer.player_name)
  return _internal_player_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GamePlayer::set_player_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.player_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game.GamePlayer.player_name)
}
inline std::string* GamePlayer::mutable_player_name() {
  std::string* _s = _internal_mutable_player_name();
  // @@protoc_insertion_point(field_mutable:game.GamePlayer.player_name)
  return _s;
}
inline const std::string& GamePlayer::_internal_player_name() const {
  return _impl_.player_name_.Get();
}
inline void GamePlayer::_internal_set_player_name(const std::string& value) {
  
  _impl_.player_name_.Set(value, GetArenaForAllocation());
}
inline std::string* GamePlayer::_internal_mutable_player_name() {
  
  return _impl_.player_name_.Mutable(GetArenaForAllocation());
}
inline std::string* GamePlayer::release_player_name() {
  // @@protoc_insertion_point(field_release:game.GamePlayer.player_name)
  return _impl_.player_name_.Release();
}
inline void GamePlayer::set_allocated_player_name(std::string* player_name) {
  if (player_name != nullptr) {
    
  } else {
    
  }
  _impl_.player_name_.SetAllocated(player_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.player_name_.IsDefault()) {
    _impl_.player_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game.GamePlayer.player_name)
}

// .game.Vec3 position = 3;
inline bool GamePlayer::_internal_has_position() const {
  return this != internal_default_instance() && _impl_.position_ != nullptr;
}
inline bool GamePlayer::has_position() const {
  return _internal_has_position();
}
inline void GamePlayer::clear_position() {
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
}
inline const ::game::Vec3& GamePlayer::_internal_position() const {
  const ::game::Vec3* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::game::Vec3&>(
      ::game::_Vec3_default_instance_);
}
inline const ::game::Vec3& GamePlayer::position() const {
  // @@protoc_insertion_point(field_get:game.GamePlayer.position)
  return _internal_position();
}
inline void GamePlayer::unsafe_arena_set_allocated_position(
    ::game::Vec3* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game.GamePlayer.position)
}
inline ::game::Vec3* GamePlayer::release_position() {
  
  ::game::Vec3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::game::Vec3* GamePlayer::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:game.GamePlayer.position)
  
  ::game::Vec3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::game::Vec3* GamePlayer::_internal_mutable_position() {
  
  if (_impl_.position_ == nullptr) {
    auto* p = CreateMaybeMessage<::game::Vec3>(GetArenaForAllocation());
    _impl_.position_ = p;
  }
  return _impl_.position_;
}
inline ::game::Vec3* GamePlayer::mutable_position() {
  ::game::Vec3* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:game.GamePlayer.position)
  return _msg;
}
inline void GamePlayer::set_allocated_position(::game::Vec3* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.position_ = position;
  // @@protoc_insertion_point(field_set_allocated:game.GamePlayer.position)
}

// int32 health = 4;
inline void GamePlayer::clear_health() {
  _impl_.health_ = 0;
}
inline int32_t GamePlayer::_internal_health() const {
  return _impl_.health_;
}
inline int32_t GamePlayer::health() const {
  // @@protoc_insertion_point(field_get:game.GamePlayer.health)
  return _internal_health();
}
inline void GamePlayer::_internal_set_health(int32_t value) {
  
  _impl_.health_ = value;
}
inline void GamePlayer::set_health(int32_t value) {
  _internal_set_health(value);
  // @@protoc_insertion_point(field_set:game.GamePlayer.health)
}

// int32 level = 5;
inline void GamePlayer::clear_level() {
  _impl_.level_ = 0;
}
inline int32_t GamePlayer::_internal_level() const {
  return _impl_.level_;
}
inline int32_t GamePlayer::level() const {
  // @@protoc_insertion_point(field_get:game.GamePlayer.level)
  return _internal_level();
}
inline void GamePlayer::_internal_set_level(int32_t value) {
  
  _impl_.level_ = value;
}
inline void GamePlayer::set_level(int32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:game.GamePlayer.level)
}

// repeated int32 inventory = 6;
inline int GamePlayer::_internal_inventory_size() const {
  return _impl_.inventory_.size();
}
inline int GamePlayer::inventory_size() const {
  return _internal_inventory_size();
}
inline void GamePlayer::clear_inventory() {
  _impl_.inventory_.Clear();
}
inline int32_t GamePlayer::_internal_inventory(int index) const {
  return _impl_.inventory_.Get(index);
}
inline int32_t GamePlayer::inventory(int index) const {
  // @@protoc_insertion_point(field_get:game.GamePlayer.inventory)
  return _internal_inventory(index);
}
inline void GamePlayer::set_inventory(int index, int32_t value) {
  _impl_.inventory_.Set(index, value);
  // @@protoc_insertion_point(field_set:game.GamePlayer.inventory)
}
inline void GamePlayer::_internal_add_inventory(int32_t value) {
  _impl_.inventory_.Add(value);
}
inline void GamePlayer::add_inventory(int32_t value) {
  _internal_add_inventory(value);
  // @@protoc_insertion_point(field_add:game.GamePlayer.inventory)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
GamePlayer::_internal_inventory() const {
  return _impl_.inventory_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
GamePlayer::inventory() const {
  // @@protoc_insertion_point(field_list:game.GamePlayer.inventory)
  return _internal_inventory();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
GamePlayer::_internal_mutable_inventory() {
  return &_impl_.inventory_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
GamePlayer::mutable_inventory() {
  // @@protoc_insertion_point(field_mutable_list:game.GamePlayer.inventory)
  return _internal_mutable_inventory();
}

// map<string, int32> skills = 7;
inline int GamePlayer::_internal_skills_size() const {
  return _impl_.skills_.size();
}
inline int GamePlayer::skills_size() const {
  return _internal_skills_size();
}
inline void GamePlayer::clear_skills() {
  _impl_.skills_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >&
GamePlayer::_internal_skills() const {
  return _impl_.skills_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >&
GamePlayer::skills() const {
  // @@protoc_insertion_point(field_map:game.GamePlayer.skills)
  return _internal_skills();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >*
GamePlayer::_internal_mutable_skills() {
  return _impl_.skills_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >*
GamePlayer::mutable_skills() {
  // @@protoc_insertion_point(field_mutable_map:game.GamePlayer.skills)
  return _internal_mutable_skills();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace game

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_game_5fplayer_2eproto
