<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="CopyRuntimeDlls" AfterTargets="Build" Condition="'$(RuntimeDllSources)' != ''">
    <ItemGroup>
      <RuntimeDll Include="$(RuntimeDllSources)" />
    </ItemGroup>
    <Copy SourceFiles="@(RuntimeDll)" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
